adds postgres version to the schema cache.
supabase-community/postgres_lsp pull request #141
Opened 2024-08-26 18:21 UTC by harshit54

Adds the postgres version in the schema cache using SQL from the `pg-meta` library.

2024-08-27 05:24 UTC, psteinroe requested changes
Thanks for the contribution! Just one minor note 🙏🏼

2024-08-27 05:24 UTC, psteinroe commented on crates/pg_schema_cache/src/versions.rs
> +        .fetch_all(pool)
why not just one row?

2024-08-27 05:24 UTC, psteinroe commented on crates/pg_schema_cache/src/schema_cache.rs
> +    pub versions: Vec<Version>,
any reason to have a Vec instead of a single struct?

2024-08-27 08:47 UTC, harshit54 commented
Hey @psteinroe , thanks for the reply.

While it does make sense to have a single type instead of a Vec, the `SchemaCacheItem` `trait` is defined as 

```rust
pub trait SchemaCacheItem {
    type Item;

    async fn load(pool: &PgPool) -> Vec<Self::Item>;
}
```
is defined as having a `Vec` of the type. Should we make the `version` implement a different trait?

2024-08-27 08:54 UTC, psteinroe commented
Ah yeah I think it makes sense to refactor this a bit. Do you want to do it in your pr or should we merge and do a follow-up? 🙏🏼

2024-08-27 09:04 UTC, harshit54 commented
Let's do a follow up. I'm not sure how the refactoring will look like at the moment.

2024-08-28 04:40 UTC, psteinroe commented
sounds good! the ci is failing due to an unrelated issue. I am going to fix it soon and then merge 🙏🏼

2024-08-29 07:15 UTC, merged